/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example; // Add this line

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        // The default App class generated by Gradle init doesn't have a getGreeting() method.
        // You might need to modify this test based on your actual App class logic.
        // For now, let's just check if the App instance is created.
        assertNotNull("app should be created", classUnderTest);
    }
}
